server:
  port: 8090

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wangle2018

  application:
    name: shiro
  mvc:
    view:
      prefix: /
      suffix: .jsp


# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  auto-mapping-behavior: full
  log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:com/example/springbootshiro/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 1
      logic-delete-value: 0